# Generated by Django 5.0.6 on 2024-06-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometraje', models.PositiveIntegerField()),
                ('condicion', models.CharField(max_length=50)),
                ('fecha_cotizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
