# Generated by Django 5.0.6 on 2024-06-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='condicion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.IntegerField(),
        ),
    ]
