# Generated by Django 5.0.6 on 2024-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_alter_vehiculo_año_alter_vehiculo_condicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='condicion',
            field=models.CharField(max_length=50),
        ),
    ]
